version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    command: rackup --host 0.0.0.0
    volumes:
      - ./:/home/project
      - backend-modules:/usr/local/bundle
    env_file: .env
    ports:
      - 9292:9292
    links:
      - postgresql
      - redis

  sidekiq:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    command: sidekiq -r ./system/boot.rb
    volumes:
      - ./:/home/project
      - backend-modules:/usr/local/bundle
    env_file: .env
    links:
      - postgresql
      - redis
      - web

  postgresql:
    image: postgres:15.0-alpine
    volumes:
      - postgres-data:/data
    env_file: .env

  redis:
    image: redis:7.0-alpine
    volumes:
      - redis-data:/data
    env_file: .env

volumes:
  backend-modules:
  postgres-data:
  redis-data:
